config/routes.rb
Rails.application.routes.draw do
  root to:'items#index'

  devise_for :users
  devise_scope :user do
    get 'users/edit_address' => 'users/registrations#edit_address'
    put 'users/update_address' => 'users/registrations#update_address'
  end

  resources :items, only: [:index, :show]
  resources :stocked_items, only: [:index, :update, :destroy] do
    collection do
      get 'order_confirmation'
    end
  end
  resources :order_histories, only: [:index, :show, :create]

  namespace :admin do
    resources :items do
      put :sort
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy]
  end
end

app/models/stocked_item.rb
class StockedItem < ApplicationRecord
  validates :add_count, numericality: { greater_than: 0 }
  belongs_to :user
  belongs_to :item

  attr_accessor :add_count

  def self.total_amount
    all.inject(0) { |sum, stocked_item| sum + stocked_item.item.price * stocked_item.count }
  end

  def self.cod_fee
    total = all.total_amount
    if total < 10000 then
      300
    elsif total < 30000 then
      400
    elsif total < 100000 then
      600
    else
      1000
    end
  end

  def self.shipping
    (1 + all.sum(:count).div(5)) * 600
  end

  def self.sales_tax
    sales_tax_rate = 8
    ((all.total_amount + cod_fee + shipping) * sales_tax_rate / 100).floor
  end

  def self.billing_amount
    all.total_amount + all.cod_fee + all.shipping + all.sales_tax
  end

  def self.delivery_date_candidates
    date = 3.days.since
    business_date_range = 12
    delivery_date_candidate = []
    business_date_range.times do
      date = date.tomorrow while (date.sunday? or date.saturday? or HolidayJapan.check(date.to_date))
      delivery_date_candidate.push(date)
      date = date.tomorrow
    end
    delivery_date_candidate
  end

  def self.delivery_time_candidates
    delivery_time_candidate = {}
    delivery_time_candidate['8時〜12時'] = '8,12'
    delivery_time_candidate['12時〜14時'] = '12,14'
    delivery_time_candidate['14時〜16時'] = '14,16'
    delivery_time_candidate['16時〜18時'] = '16,18'
    delivery_time_candidate['18時〜20時'] = '18,20'
    delivery_time_candidate['20時〜21時'] = '20,21'
    delivery_time_candidate
  end

  after_initialize do
    self.add_count = 1
  end

  before_update do
    self.count += self.add_count.to_i
  end
end

app/controllers/stocked_items_controller.rb
class StockedItemsController < ApplicationController
  before_action :set_stocked_items_all, only: [:index, :order_confirmation]
  before_action :set_stocked_items, only: [:update, :destroy]

  def index
  end

  def show
  end

  def update
    if @stocked_item.update(stocked_item_params)
      redirect_to stocked_items_path, notice: 'ショッピングカートに追加しました。'
    else
      @item = Item.active.find(stocked_item_params[:item_id])
      render 'items/show'
    end
  end

  def destroy
    @stocked_item.destroy
    redirect_to stocked_items_url, notice: 'ショッピングカートから削除しました。'
  end

  def order_confirmation
    if current_user.stocked_items.blank?
      redirect_to stocked_items_url, notice: 'ショッピングカートに商品を追加してください。'
    end
  end

  private
    def set_stocked_items_all
      @stocked_items = current_user.stocked_items.all
    end

    def set_stocked_items
      @stocked_item = current_user.stocked_items.find(params[:id])
    end

    def stocked_item_params
      params.require(:stocked_item).permit(:item_id, :add_count)
    end
end

app/views/stocked_items/index.html.haml
%h1 ショッピングカート

%table.table.table-bordered.table-striped
  %thead
    %tr
      %th 商品画像
      %th 商品名
      %th 価格
      %th 個数
      %th.col_buttons 操作

  %tbody
    - @stocked_items.order(:id).each do |stocked_item|
      %tr
        %td
          .item_image_frame_small= image_tag(stocked_item.item.image, class: 'img-rounded', alt: stocked_item.item.name)
        %td= stocked_item.item.name
        %td= price_format(stocked_item.item.price)
        %td= stocked_item.count
        %td
          = link_to '商品ページ', item_path(stocked_item.item), class: 'btn btn-info'
          = link_to '削除', stocked_item, method: :delete, data: { confirm: '商品を削除してよろしいですか？' }, class: 'btn btn-danger'

%br

=link_to '注文確認に進む', order_confirmation_stocked_items_path, class: 'btn btn-primary'

app/views/stocked_items/order_confirmation.html.haml
%h1 注文確認

%table.table.table-bordered.table-striped
  %thead
    %tr
      %th 商品画像
      %th 商品名
      %th 価格
      %th 個数
      %th.col_buttons 操作

  %tbody
    - @stocked_items.order(:id).each do |stocked_item|
      %tr
        %td
          .item_image_frame_small= image_tag(stocked_item.item.image, class: 'img-rounded')
        %td= stocked_item.item.name
        %td= price_format(stocked_item.item.price)
        %td= stocked_item.count
        %td= link_to '商品ページ', item_path(stocked_item.item), class: 'btn btn-info'

.row
  .col-md-6
    %h1= '請求金額'
    %table.table.table-bordered.table-striped
      %tr
        %th 合計金額
        %td= price_format(@stocked_items.total_amount)
      %tr
        %th 代引き手数料
        %td= price_format(@stocked_items.cod_fee)
      %tr
        %th 送料
        %td= price_format(@stocked_items.shipping)
      %tr
        %th 消費税
        %td= price_format(@stocked_items.sales_tax)
      %tr
        %th 請求金額
        %td= price_format(@stocked_items.billing_amount)

  .col-md-6
    %h1= '送付先'
    %table.table.table-bordered.table-striped
      %tr
        %th 名前
        %td= current_user.name
      %tr
        %th 郵便番号
        %td= current_user.zip
      %tr
        %th 住所
        %td= current_user.address
    = link_to '送付先を変更する', users_edit_address_path, class: 'btn btn-primary'
%br

- order_history = current_user.order_histories.build
= simple_form_for order_history do |f|
  - if @order_history != nil && @order_history.errors.any?
    %ul
      - @order_history.errors.full_messages.each do |message|
        %li.msg_error= message
  .field
    = f.label '配送希望日'
    = f.select :delivery_date, @stocked_items.delivery_date_candidates.map{ |d| [date_format(d), d] }
    = f.select :delivery_time, options_for_select(@stocked_items.delivery_time_candidates)
  %br
  = f.button :submit, '注文を確定する', class: 'btn btn-warning'
%br

=link_to '商品一覧に戻る', items_path
\|
=link_to 'ショッピングカートに戻る', stocked_items_path 