config/routes.rb
Rails.application.routes.draw do
  root to:'items#index'

  devise_for :users
  devise_scope :user do
    get 'users/edit_address' => 'users/registrations#edit_address'
    put 'users/update_address' => 'users/registrations#update_address'
  end

  resources :items, only: [:index, :show]
  resources :stocked_items, only: [:index, :update, :destroy] do
    collection do
      get 'order_confirmation'
    end
  end
  resources :order_histories, only: [:index, :show, :create]

  namespace :admin do
    resources :items do
      put :sort
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :stocked_items, dependent: :destroy
  has_many :order_histories, dependent: :destroy
  validates :email, presence: true
  validates :name, presence: true
  validates :zip, length: { maximum: 7 }

  def admin?
    # コードレビューのため、初回登録ユーザーを管理者ユーザーとする
    is_admin? || id == 1
  end

  def update_without_current_password(params, *options)
    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end

    clean_up_passwords
    update_attributes(params, *options)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  layout 'admin'
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def update
    if @user.update_without_current_password(user_params)
      redirect_to admin_user_path(@user), notice: 'ユーザー情報を更新しました。'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_url, notice: 'ユーザーを削除しました。'
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :name, :zip, :address, :password, :password_confirmation)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  prepend_before_action :authenticate_scope!, only: [:edit, :update, :destroy, :edit_address]

  def edit_address
  end

  def update_address
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)

    resource_updated = update_resource(resource, account_update_params)
    if resource_updated
      redirect_to order_confirmation_stocked_items_path, notice: '送付先を更新しました。'
    else
      render :edit_address
    end
  end
end

app/views/admin/users/edit.html.haml
.col-md-5
  %h1 ユーザー情報編集
  .under_space
    = simple_form_for [:admin, @user] do |f|
      = f.input :email
      = f.input :name
      = f.input :zip
      = f.input :address
      = f.input :password
      = f.input :password_confirmation
      = f.button :submit, class: 'btn btn-primary'
  = link_to '詳細', admin_user_path(@user)
  \|
  = link_to 'ユーザー一覧に戻る', admin_users_path

app/views/admin/users/index.html.haml
%h1 ユーザー一覧

%table.table.table-bordered.table-striped
  %thead
    %tr
      %th メールアドレス
      %th 名前
      %th 郵便番号
      %th 住所
      %th.col_buttons 操作

  %tbody
    - @users.order(:id).each do |user|
      %tr
        %td= user.email
        %td= user.name
        %td= user.zip
        %td= user.address
        %td
          =link_to '詳細', admin_user_path(user), class: 'btn btn-info'
          = link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary'
          = link_to '削除', admin_user_path(user), :method => :delete, :data => { :confirm => 'ユーザー情報を削除してよろしいですか？' }, class: 'btn btn-danger'

app/views/admin/users/show.html.haml
%p
  %b メールアドレス:
  = @user.email
%p
  %b 名前:
  = @user.name
%p
  %b 郵便番号:
  = @user.zip
%p
  %b 住所
  = @user.address

= link_to '編集', edit_admin_user_path(@user)
\|
= link_to 'ユーザー一覧に戻る', admin_users_path