config/routes.rb
Rails.application.routes.draw do
  root to:'items#index'

  devise_for :users
  devise_scope :user do
    get 'users/edit_address' => 'users/registrations#edit_address'
    put 'users/update_address' => 'users/registrations#update_address'
  end

  resources :items, only: [:index, :show]
  resources :stocked_items, only: [:index, :update, :destroy] do
    collection do
      get 'order_confirmation'
    end
  end
  resources :order_histories, only: [:index, :show, :create]

  namespace :admin do
    resources :items do
      put :sort
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy]
  end
end

app/views/layouts/admin.html.haml
- content_for :content do
  .col-md-3.sidebar
    .panel.panel-default
      .panel-heading 
        設定項目
      .panel-body
        .collapse.navbar-collapse
        %ul.nav.navbar-sidebar
          %li= link_to '商品管理', admin_items_path
          %li= link_to 'ユーザー管理', admin_users_path
  .col-md-9
    = yield
= render template: 'layouts/application'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title さくらマーケット
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-default
      .navbar-header
        %a.navbar-brand{href: items_path} さくらマーケット
      .collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li
              %p.navbar-text
                Login as 
                %strong= current_user.email
            %li
              = link_to 'ショッピングカート', stocked_items_path
            %li
              = link_to '購入履歴', order_histories_path
            %li
              = link_to 'プロフィール変更', edit_user_registration_path
            - if current_user.admin?
              %li
                = link_to '管理者画面', admin_items_path
            %li
              = link_to 'ログアウト', destroy_user_session_path, method: :delete
          - else
            %li
              = link_to '新規登録', new_user_registration_path
            %li
              = link_to 'ログイン', new_user_session_path
    %main(role='main' class='container-fluid')
      - if notice
        %p.notice= notice
      - if alert
        %p.alert= alert
      = content_for?(:content) ? yield(:content) : yield